---
  - name: Laravel Dev Configuration with Ansible
    hosts: all
    sudo: True
    vars:
        doc_root: var/www/html
        db: mariadb
        mariadb:
            install: '1'
            root_password: ''
            database: PrendoPosta
            user: root
            password: P4ssw0rd1!
            dump: ''
    pre_tasks:
      - name: update apt cache
        apt: update_cache=yes
    roles:
      - httpd
      - database
      - webserver
      - common
