---
  - name: Easy Dev Configuration with Ansible
    hosts: all
    sudo: True
    vars:
        document_root: /vagrant
        server_admin: andrea.speziale@top-ix.com
    tasks:
      - name: update apt cache
        apt: update_cache=yes
      - include: tasks/php.yml
      - include: tasks/git.yml
      - include: tasks/mysql.yml
      - include: tasks/apache.yml
