---
  - name: Easy Dev Configuration with Ansible
    hosts: all
    sudo: True
    pre_tasks:
      - name: Pre-task | Update apt cache
        apt: update_cache=yes
    roles:
      - webserver
      - database
      - common
