---
  - name: Laravel Dev Configuration with Ansible
    hosts: all
    sudo: True
    vars:
        document_root: /vagrant/learning-laravel-5/public
        symbolic_link_phpMyAdmin: /vagrant/learning-laravel-5/
        db: mysql
    pre_tasks:
      - name: update apt cache
        apt: update_cache=yes
    roles:
      - database
      - webserver
      - common
