---
  - name: Easy Dev Configuration with Ansible
    hosts: all
    sudo: True
    vars:
        server_name: myproject.top-ix.org
        server_admin: andrea.speziale@top-ix.com
        document_root: /vagrant
    handlers:
      - name: reload apache
        service: name=apache2 state=reloaded
    tasks:
      - name: update apt cache
        apt: update_cache=yes
      - include: tasks/vim.yml
      - include: tasks/php.yml
      - include: tasks/git.yml
      - include: tasks/mysql.yml
      - include: tasks/apache.yml
