---
  - name: Gearbox Dev Configuration with Ansible
    hosts: all
    sudo: True
    pre_tasks:
      - name: update apt cache
        apt: update_cache=yes
    roles:
      - python
      - database
      - webserver
      - common
      - virtualenv
