---
- name: install php
  apt: pkg={{ item }} state=installed
  with_items:
    - php5-fpm
    - php5-cli
    - php5-common
    - php5-curl
    - php5-json
    - php-pear
    - php5-gd
    - php5-mcrypt
    - php5-mysql
    - php5-xmlrpc
    - libapache2-mod-php5
- name: install phpMyAdmin
  apt: pkg={{ item }} state=present
  with_items:
    - phpmyadmin
    - libmysqlclient-dev
- name: symbolic link for phpMyAdmin
  shell: ln -s /usr/share/phpmyadmin /var/www/html/
